### ISSUE TITLE
Add argument for length of year to compute annual statistics on parts of yeara

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [bcgov/fasstr#78]
The current code has a start_water_year parameter to allow for years that don't start in January.
Consider adding "months_in_year=12" as a new parameter to allow for annual statistics on parts of years.

For example, if you wanted annual statistics on April -> July data, you would specify start_water_year=4 and
months_in_year=4.

This add additional flexibility in the computations.

Carl Schwarz

**Comment by jongoetz** [comment]
Added existing "months" argument from some fasstr functions to all relevant functions. Instead of listing the number of months from the start of the year, the specific months by number (1=Jan, 5=May, 12=Dec) are listed- examples: 1:4 for Jan-April, or c(1,3,5:8) for Jan, Mar, May-Sep (unrealistic example but example of functionality).

See commit bbdd4fe307e922ab12e2be35561b1de9ab8fc86b and other previous commits.
Will push to CRAN when ready.

**Comment by jongoetz** [comment]
months argument now available on most functions on CRAN version!

**Comment by cschwarz-stat-sfu-ca** [comment]
Hmmm... but how will you distinguish between contiguous months of  Nov, Dec of year t plus January, Feb of year t+1 (a 4 month span) from a non-contiguous span of Jan,Feb and then Nov, Dec (i.e. first 2 months of year t plus last 2 months of year t)? Is the latter every a sensible thing to do? If not, then as long as the documentation is clear that months=c(1:2,11:12) involves two separate calendar years, then it should be ok.  Carl

**Comment by cschwarz-stat-sfu-ca** [comment]
I also notice that the documentation says
   @param months  Numeric vector  ... Leave blank to plot  all months (default \code{1:12})

The phrase "leave blank" is ambiguous.  I assume that that the arguments to the function have a default value of months=1:12, so if you don't specify this argument, the default takes place. Better wording is 
    .... Default value will plot all months.
so that the person is not confused by "leave blank".

**Comment by jongoetz** [comment]
Great points to make, Carl! Thanks for the suggestions. I will update the documentation to make it more clear on both counts. 

You are correct that for the first 4 months for a year starting in November, `water_year_start = 11`, you would list `months=c(1:2,11:12)`, or even `c(11:12,1:2)` for consecutive order. I had considered your suggestion, but I already had the 'months' argument as it is throughout the package and wanted to keep that functionality for existing fasstr user workflows going forward.  

For workflows that want to list the number of months from the start of year instead of naming the months per fasstr usage,  a function like below (or similar) could be incorporated to the code. I will likely add this example in a vignette for reference for others, along with updating the documentation wording.

```
### Function for number of months from start
months_from_start <- function(water_year_start, number_months){
  c(1:12,1:12)[water_year_start:(water_year_start+(number_months-1))][1:min(12,number_months)]
}

### Set water year start and number of months
water_year_start = 11
number_months = 4
months <- months_from_start(water_year_start, number_months)
months

### Apply function (or new months value) to months argument in function
calc_longterm_daily_stats(station_number = "08HB048",
                          complete_years = TRUE,
                          water_year_start = water_year_start,
                          months = months)
```
