### ISSUE TITLE
Add argument for allowable % missing values

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [bcgov/fasstr#79]
At the moment, the ignore.missing argument is completely binary so even if a year is missing a single value, the statistics for the year are not computed.

Generalize this parameter to the allowable percentage of missing values, e.g. allowable_per_missing=5 would imply that statistics would still be computed if 5% of daily observations are missing. allowable_per_missing=0 and allowable_per_missing=100 would be the two extremes indicated by the current ignore.missing=FALSE and TRUE.

Carl Schwarz

**Comment by jongoetz** [comment]
Added "allowed_missing" argument to relevant functions - annual and monthly functions that calculate and plots means, percentiles, maximums and minimums (eg. calc_annual_stats(), plot_monthly_stats() and others). Not used with cumulative, days_outside_normal, or timing functions, nor daily or long-terms statistics due to different groupings. 

Works seamlessly with existing ignore_missing argument to maintain functionality: if ignore_missing = FALSE then allowed_missing = 0 by default, if ignore_missing = TRUE then allowed_missing = 100. Changing allowed_missing will override ignore_missing otherwise.

See commit 5a78ffcd722a83e9026aed71e0249fd620e631b1.
Will push to CRAN when ready.

**Comment by jongoetz** [comment]
Now available on CRAN version!
